CREATE TABLE locations (
  value text PRIMARY KEY
);

INSERT INTO locations VALUES ('BARCELONA');
INSERT INTO locations VALUES ('DUESSELDORF');
INSERT INTO locations VALUES ('BERLIN');
INSERT INTO locations VALUES ('DORTMUND');
INSERT INTO locations VALUES ('COPENHAGEN');
INSERT INTO locations VALUES ('MUNICH');
INSERT INTO locations VALUES ('MUENSTER');
INSERT INTO locations VALUES ('CURITIBA');
INSERT INTO locations VALUES ('AACHEN');
INSERT INTO locations VALUES ('MEDELLIN');
INSERT INTO locations VALUES ('HAMBURG');
